# Spring Boot 应用配置
server.port=8080
server.servlet.context-path=/

# 日志配置
logging.level.root=INFO
logging.level.com.bolingcavalry=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
# 日志编码配置，解决中文乱码问题
logging.charset.console=UTF-8
logging.charset.file=UTF-8
# 应用名称
spring.application.name=rag-clickhouse-index

# rag文件路径
rag.file.path=/home/will/temp/202601/01

# clickhouse数据库连接地址
clickhouse.url=http://localhost:8123
# clickhouse数据库表名
clickhouse.table=langchain4j_table
# clickhouse数据库用户名
clickhouse.username=admin
# clickhouse数据库密码
clickhouse.pswd=123456